openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is the API documentation for the Contacts Management system.
    Provides endpoints for CRUD operations, photo uploads, favorites,
    contact categorization (work, personal, home), filtering and sorting.
    Requires Bearer token authentication.
tags:
  - name: Contacts
    description: Operations with contacts (CRUD, filtering, etc).
  - name: Auth
    description: User authentication and authorization.
servers:
  - url: http://127.0.0.1:8080
    description: Local server
  - url: https://nodejs-hw-mongodb-4maf.onrender.com
    description: Production server
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.post.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/sendResetEmail.post.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/resetPwd.post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionId
